In [2]:
import numpy as np

In [17]:
arr = np.array(42)   # 0-D array
a = np.array([1,2])   #1-D array
b = np.array([[1,2,3], [4,5,6]])   #3-D array
print(b)
print("Dimension of array b:",b.ndim)

[[1 2 3]
 [4 5 6]]
Dimension of array b: 2


In [19]:
#An array can have any number of dimensions
#When the array is created, you can define the number of dimensions by using the ndmin argument.

arr = np.array([1,2,3,4], ndmin=4)
print(arr)
print("Number of dimensions of arr:", arr.ndim)


[[[[1 2 3 4]]]]
Number of dimensions of arr: 4


In [24]:
#Accessing arrays
a = np.array([1,2,3])
print(a[2])

b = np.array([[1,2,4], [5,6,7]])
print(b[0,2])

#Negative Indexing
print(b[1,-3], b[1,-1])

3
4
5 7


In [32]:
#Slicing Arrays
#We pass slice instead of index like this: [start:end].
#We can also define the step, like this: [start:end:step]

arr = np.array([1,2,3,4,7,8,9])
print(arr[1:5])   #end is exclusive
print(arr[3:])   #will print until the end of the array
print(arr[:4])   #will print from the beginning of the array till index 3

#Negative Slicing
print(arr[-6:-3])
print(arr[-1:-4])


#Step
print("Step:", arr[1:6:2])
print(arr[::2])   #Return every other element in 2 steps

[2 3 4 7]
[4 7 8 9]
[1 2 3 4]
[2 3 4]
[]
Step: [2 4 8]
[1 3 7 9]


In [38]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0,0:3])
print(arr[0:2, 3])   #From both the lists, return the index 3

arr2 = np.array([[2,4,6,8], [1,3,6,9], [12,13,14,15]])
print(arr2[0:3, 2:4])

[1 2 3]
[4 9]
[[ 6  8]
 [ 6  9]
 [14 15]]


In [43]:
#Data types in Numpy
arr = np.array([1,2,3,4])
print(arr.dtype)   #32-bit signed integer, Stores values from (-2^31 to 2^31 -1)

arr2 = np.array(['apple', 'banana'])
print(arr2.dtype)

int32
<U11


In [45]:
#Creating array with a defined data type
arr = np.array([2,3,4], dtype="S")
print(arr)
print(arr.dtype)

#Creating an array with data type 4 bytes integer
arr2 = np.array([1,2,3,4], dtype='i8')
print(arr2)
print(arr2.dtype)

[b'2' b'3' b'4']
|S1
[1 2 3 4]
int64


In [66]:
b = np.array([1,2,3], dtype = complex)
print(b)

[1.+0.j 2.+0.j 3.+0.j]


In [49]:
#Converting Data type on Existing arrays
#Using astype function

arr = np.array([1.1, 2.3])
newarr = arr.astype('i')
#newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

arr2 = np.array([1,0,3, -1])
newarr2 = arr2.astype(bool)
print(newarr2)
print(newarr2.dtype)

[1 2]
int32
[ True False  True  True]
bool


In [60]:
#Difference between Copy and View
#The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

#The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

print("Copy: \n")
arr = np.array([1,2,3,4])
x = arr.copy()

arr[2] = 99

print(arr)
print(x)

x[3] = 78
print(x)

#View
print("\nView: \n")
arr2 = np.array([2,4,6,8])
y = arr2.view()
arr2[3] = 99
y[0] = 65

print(arr2)
print(y)

#If we make a change in the view array, the change will also be reflected in the original array

#.base - to check whether an array owns its data or not
print("\nWorking with base: \n")
z = np.array([1,2,3])

p = z.copy()
q = x.view()

print(p.base)
print(q.base)

Copy: 

[ 1  2 99  4]
[1 2 3 4]
[ 1  2  3 78]

View: 

[65  4  6 99]
[65  4  6 99]

Working with base: 

None
[ 1  2  3 78]


In [65]:
#Shape

arr = np.array([[2,4,6,8], [1,3,6,9], [12,13,14,15]])
print(arr.shape)
#The example above returns (3, 4), which means that the array has 2 dimensions, where the first dimension has 3 elements and the second has 4.


arr2 = np.array([[[1,2,3,4], [1,2,3,4], [1,2,3,4]], [[1,2,3,4], [1,2,3,4], [1,2,3,4]]])
print(arr2.shape)

arr3 = np.array([1,2,3,4], ndmin = 5)
print("arr3:", arr3)
print(arr3.shape)

(3, 4)
(2, 3, 4)
arr3: [[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [19]:
np.arange(1.5, 4, 0.5) #Generate a sequence starting with 1.5 with width 0.5 and excluding 4

array([1.5, 2. , 2.5, 3. , 3.5])

In [72]:
arr = np.empty((2,3)) #empty() function is used to return new array of a given shape and type. It has random values and uninitialized entries.
print(arr)
print(arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [79]:
arr = np.zeros((4,2,3))   #default dtype is 'float'
print(arr, "\n")

y = np.zeros((4,5), dtype=int)   #typecasting to int
print(y)

np.ones_like(y)   #Initializing the array to 1
np.ones_like(y, dtype=float)   #Initializing the array to 0 with data type float

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] 

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [94]:
print(list(range(7)))   #printing a list of size 7 starting from 0 with width 1
print(tuple(range(4)))  #printing a tuple of size 4 starting from 0 with width 1

#arange
print(np.arange(2, 20, 3))   #Generate a sequence starting with 2 with width 3 and excluding 20

np.arange(2.0, 10, 1.5, dtype= int)

[0, 1, 2, 3, 4, 5, 6]
(0, 1, 2, 3)
[ 2  5  8 11 14 17]
[ 1  3  5  7 10]


In [99]:
#linspace
print(np.linspace(1, 10, 5, dtype=int))   #divide the interval 1 to 10 into 5 equally spaced divisions
x = np.linspace(1,20,10, retstep = True)
print(x)

y = np.linspace(0, 5, 10)
z = np.linspace(0, 5, 10, endpoint = False)   #endpoint to false will omit the last point in the sequence

print("y:", y)
print("z:", z)

[ 1  3  5  7 10]
(array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ]), 2.111111111111111)
y: [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
z: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [104]:
#Initializing an Array from a Function
def f(i, j):
    return 2*i*j

x = np.fromfunction(f, (4,3))   #(4,3) is the dimension of the matrix, i.e, 3 columns and 4 rows
print(x)

#A more consise way of writing the function
y = np.fromfunction(lambda i,j: 2*i*j, (4,4))
print("\n", y)

[[ 0.  0.  0.]
 [ 0.  2.  4.]
 [ 0.  4.  8.]
 [ 0.  6. 12.]]

 [[ 0.  0.  0.  0.]
 [ 0.  2.  4.  6.]
 [ 0.  4.  8. 12.]
 [ 0.  6. 12. 18.]]


In [112]:
#Universal Functions
#Universal functions in Numpy are simple mathematical functions. 
#It is just a term that we gave to mathematical functions in the Numpy library. 
#Numpy provides various universal functions that cover a wide variety of operations.

x = np.linspace(1,5,5)
print("Original:", x)

print("x**3 = ", x**3)   #each element in the array is raised to the power of 3

print("x-1 = ", x -1)    #each element of the array is subtracted by 1

print(np.sqrt(x-1))      #The square root of each element is taken

y = np.exp(-np.linspace(0,2,5))
#The interval from 0 to 2 is equally divided into 5 divisions
#The exponential of the negation of those numbers are taken
print("\ny:", y)

print(np.sin(x-y))

Original: [1. 2. 3. 4. 5.]
x**3 =  [  1.   8.  27.  64. 125.]
x-1 =  [0. 1. 2. 3. 4.]
[0.         1.         1.41421356 1.73205081 2.        ]

y: [1.         0.60653066 0.36787944 0.22313016 0.13533528]
[ 0.          0.98431873  0.48771645 -0.59340065 -0.98842844]


In [129]:
#Matrix Multiplication in numpy
a = np.array([[1,2], [2,1]])
b = np.array(((1,2), (2,1)))

print(a*b)   #Element-wise multiplication

c = np.array([[1,2], [3,4]])
print("\nc:", c)
print("\nc.T:", c.T)   #Transpose of matrix c

print("\nMatrix Multiplication between a and b:\n", np.matmul(a,b))
print("\nDot Product:\n", a.dot(b))   #also np.dot(a,b)
#For 1-D arrays, dot product acts as the inner product of the vectors
#For 2-D arrays, it acts as matrix multiplication


[[1 4]
 [4 1]]

c: [[1 2]
 [3 4]]

c.T: [[1 3]
 [2 4]]

Matrix Multiplication between a and b:
 [[5 4]
 [4 5]]

Dot Product:
 [[5 4]
 [4 5]]

Dot product between a and b: [ 5  8 11]


In [134]:
#Comparison and Logic Opera
a = np.array([[1,2,3], [2,3,4]])
b = np.array([1,2])
print("\nDot product between a and b:", np.dot(b,a))

print(a>2)   #returns a boolean for each element-wise comparison 
print((a<2) | (a>100))


Dot product between a and b: [ 5  8 11]
[[False False  True]
 [False  True  True]]
[[ True False False]
 [False False False]]


In [142]:
#Flatten and Ravel
a = np.array([[1,2,3], [4,5,6]])
b = a.flatten()   #Creates an independent, flattened copy of a
print(a)
print(b)

b[2] = 99
print("\nModified b: ", b)
print("a:", a)

#Ravel
c = a.ravel()   #c only presents a view of a. Any changes made to c will be reflected in a 
print("\nOriginal c:", c)

c[3] = 108
print("Modified c:", c)
print(a)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]

Modified b:  [ 1  2 99  4  5  6]
a: [[1 2 3]
 [4 5 6]]

Original c: [1 2 3 4 5 6]
Modified c: [  1   2   3 108   5   6]
[[  1   2   3]
 [108   5   6]]


In [152]:
#Resize and Reshape
#resize - inverse of flatten
#reshape - returns a view of the array with its elements reshaped as required.

a = np.linspace(1,8,8)
print(a)

print(a.resize(2,2,2))   #Doesn't return anything
a.resize(2,2,2)
a

b = np.linspace(1,4,4)
c = b.reshape(2,2)
print(c)

c[0,1] = 9
print("c:", c)
print("b:", b)


[1. 2. 3. 4. 5. 6. 7. 8.]
None
[[1. 2.]
 [3. 4.]]
c: [[1. 9.]
 [3. 4.]]
b: [1. 9. 3. 4.]


In [4]:
#Transposing an array
#the method transpose returns a view of an array with its axes transposed

a = np.linspace(1,16,16)
b = a.reshape(2,2,4)
print(a)
print(a.transpose())   # Transposing a 1-D array returns the array unchanged
print("\nb:",b)
print("\nb transpose: \n", b.transpose())
print("\nSize of b transpose:", b.transpose().shape)

print("\nb transpose: \n", b.T)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]

b: [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]

b transpose: 
 [[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]

Size of b transpose: (4, 2, 2)

b transpose: 
 [[[ 1.  9.]
  [ 5. 13.]]

 [[ 2. 10.]
  [ 6. 14.]]

 [[ 3. 11.]
  [ 7. 15.]]

 [[ 4. 12.]
  [ 8. 16.]]]


In [21]:
#Merging and Splitting Arrays
#
a = np.array([2,3,4])
b = np.array([1,1,1])
c = np.array([10,20,30])
d = np.vstack((a,b))
e = np.dstack((a,b,c))
f = np.hstack((a,b))
print("d:",d)
print("\ne:",e)
print("\nf:",f)
print(e.shape)

print(np.vsplit(d,2))
print(np.hsplit(f,2))

d: [[2 3 4]
 [1 1 1]]

e: [[[ 2  1 10]
  [ 3  1 20]
  [ 4  1 30]]]

f: [2 3 4 1 1 1]
(1, 3, 3)
[array([[2, 3, 4]]), array([[1, 1, 1]])]
[array([2, 3, 4]), array([1, 1, 1])]


In [28]:
#Indexing and Slicing of Array
a = np.linspace(1,10,10, dtype=int)
print('a:', a)
print(a[2:7:2])   #stride of 2 from index 2 to index 6
print(a[2::3])    #stride of 2 from index 2 till the end
print(a[5::-1])   #stride of -1 from index 5 till the beginning

a: [ 1  2  3  4  5  6  7  8  9 10]
[3 5 7]
[3 6 9]
[6 5 4 3 2 1]


In [40]:
a = np.linspace(1,12,12).reshape(4,3)
print(a)
print("\n", a[2,:])   #print the 3rd row of a
print("\n", a[:,1])   #print all the elements having index 1 from all the rows
print("\n", a[1:, 1:3])   #print as from the 2nd row all the elements having indices 1 and 2

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]

 [7. 8. 9.]

 [ 2.  5.  8. 11.]

 [[ 5.  6.]
 [ 8.  9.]
 [11. 12.]]


In [44]:
a = np.linspace(1,12,12)
b = a.reshape(4,3)
print("a:"a)
ia = [1,4,5]
print(a[ia])   #will print the elements having the indices specified in ia
print("\nb:",b)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[2. 5. 6.]

b: [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [50]:
#Broadcasting
a = np.array([2,4,6])
print(a+5)

M = np.ones((3,3))
print("M:",M)
print("\nM+a:", M+a)

[ 7  9 11]
M: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

M+a: [[3. 5. 7.]
 [3. 5. 7.]
 [3. 5. 7.]]


In [11]:
#Maximum and Minimum Values
arr = np.array([2,4,6,8,10])
print(np.argmax(arr))   #will print the index of the largest number
print(np.argmin(arr))   #will print the index of the least number

print(np.max(arr))    #will print the largest number in the array
print(np.min(arr))    #will print the least number in the array


a = np.array([[2,0,-1,5], [3,7,9,10], [5,10,15,34]])

print(a.max(axis = 0))   #will print the maxima from each column
print(a.min(axis = 1))   #will print the minima from each row

4
0
10
2
[ 5 10 15 34]
[-1  3  5]


In [22]:
#Sorting an Array
arr = np.array([5,-1,100,67,2])
a = arr.sort()
print("Sorted arr: \n", arr)

arr2 = np.array([[10,6,2,1], [67,-100,-23,2], [4,5,1,-9]])
arr2.sort()
print("\nSorted arr2: \n",arr2)
arr2.sort(axis=0)   #The columns of the array are sorted
print("\narr2 Sorted column wise:\n", arr2)

Sorted arr: 
 [ -1   2   5  67 100]

Sorted arr2: 
 [[   1    2    6   10]
 [-100  -23    2   67]
 [  -9    1    4    5]]

arr2 Sorted column wise:
 [[-100  -23    2    5]
 [  -9    1    4   10]
 [   1    2    6   67]]


In [38]:
a = np.array([3,0,-100,-23])
print(np.argsort(a))   #will print the index of the sorted list

b = np.array([1,2,3,4])
print(np.searchsorted(b,2.5))   #will print out the index postion where the number mentioned as the 2nd parameter will be inserted 
                                #such that the order of the array is preserved
print(np.searchsorted(b, (0, 1.5, 3.5)))    

[2 3 1 0]
2
[1 2 3 4]


In [47]:
#Maxima and Minima
a = np.sqrt(np.linspace(-2,2,4))
print(a)
print(np.min(a), np.max(a))
print(np.nanmin(a), np.nanmax(a))
print(np.argmin(a), np.argmax(a))
print(np.nanargmin(a), np.nanargmax(a))

b = np.array([2,4,6,-1, -10])
c = np.array([-1,5,3,0,9])

print(np.fmax(b,c))   #will compare each element of both arrays having the same index and print the maximum value
print(np.fmin(b,c))   #will compare each element of both arrays having the same index and print the minimum value 

[       nan        nan 0.81649658 1.41421356]
nan nan
0.8164965809277259 1.4142135623730951
0 0
2 3
[2 5 6 0 9]
[ -1   4   3  -1 -10]


C:\Users\saivi\AppData\Local\Temp\ipykernel_8748\3960462800.py:2: RuntimeWarning: invalid value encountered in sqrt
  a = np.sqrt(np.linspace(-2,2,4))


In [51]:
#Percentile
a = np.array([[0,0.6,1.2], [1.8,2.4,3.0]])
print(np.percentile(a, q=100))   #will print the maximum value of the array
print(np.percentile(a,50))   #will print the median of the array
print(np.percentile(a, 50, axis = 0))   # will print the median of each column

3.0
1.5
[0.9 1.5 2.1]


In [56]:
#Sample Statistics
a = np.array([1,4,6,10])
print(np.mean(a))   #will calculate the arithmetic mean of the values in the array
print(np.median(a)) #will calculate the arithmetic median of the values of the array
print(np.average(a, weights=[2, 0.3, 2, 0]))   #will calculate the weighted average
print(np.var(a))   #will calculate the variance
print(np.std(a))   #will calculate the standard deviation
print(np.std(a, ddof=1))   #will calculate the standard deviation
#ddof = delta degree of freedom - maximum number of logically independent values


5.25
5.0
3.5348837209302326
10.6875
3.2691742076555053
3.774917217635375


In [61]:
#Special Distributions
#np.random() - generate random numbers from any of several dsitributions
print(np.random.randint(1,10,10))   #print random integets from [1,10]
print(np.random.rand(2,3))   #creates an 2x3 array with random values
print(np.random.randint(10)) #prints a random integer from [0.10]
print(np.random.normal(loc=5, size=3)) #selects a random value from the normal distribution
#having mean = 'loc' and s.d = 'scale'


[2 2 3 6 3 1 7 9 7 8]
[[0.88962207 0.93870049 0.8771474 ]
 [0.76639505 0.26797963 0.31583654]]
1
[4.6415078  6.42162071 2.8930879 ]
